---
title: What I'm Reading
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    excerpt_separator: "<!--more-->"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header_feature_image:
    caption:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    header_feature_image:
    caption:
- scope:
    path: ''
    type: recipe
  values:
    layout: recipe
    order:
baseurl: ''
url: https://spencerchantelois.github.io
description: A website with blog posts
avatar: assets/img/face.jpg
favicon: assets/favicon.ico
gridlayout: false
recipemenu: false
header_text: Random Book Reviews
recipecollection: Campfire Chef
header_feature_image: "/uploads/Darwin.jpg"
recipe_bookcover: "/uploads/CookbookCover1.jpg"
twitter_username:
lang: en_gb
footer_text: Copyright 2020 Spencer Chantelois, header photo - Darwin Vegher on Unsplash
rss: false
email_address:
facebook:
flickr:
google_plus:
instagram:
linkedin:
pinterest:
soundcloud:
twitter:
youtube:
share_buttons:
  facebook: true
  twitter: true
  tumblr:
  pinterest:
  linkedin:
  email: true
google_analytics:
disqus_shortname:
str_follow_on: Follow on
str_rss_follow: Follow RSS feed
str_share_on: Share on
str_add_to: Add to
str_email: Email
str_tweet: Tweet
str_pin_it: Pin it
str_next_post: Next post
str_previous_post: Previous post
str_next_page: Next
str_previous_page: Prev
str_javascript_required_disqus: Please enable JavaScript to view comments.
post_navigation: true
paginate: 10
paginate_path: blog/page:num
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- ".jekyll-cache"
- Gemfile
- README.md
